Feat/bot
russtrUA/currency-bot pull request #1
Opened 2024-07-21 11:13 UTC by ruslanaprus

Додано BACK_TO_MAIN_BUTTON до констант, щоб розрізняти 2 різні меню - головне меню та меню налаштувань.

У класі `KeyboardFactory` методи, які повертають клавіатуру для кожного меню, мають єдиний параметр `UserSettings userSettings`. Опис налаштувань отримується шляхом виклику геттерів із класу `UserSettings`.

У класі `CallbackHandler` об’єкт `UserSettingsProvider` використовується для отримання та оновлення параметрів для конкретного користувача. Як можливу реалізацію цієї функції я використала методи `getAllUserSettings(long userId)` і `setUserSettingsByid(long userId, UserSettings userSettings)` у класі `UserSettingsProvider`.

У класі `CallbackHandler` додано об’єкт `CurrencyRateProvider`, щоб мати можливість отримувати дані про обмінні курси, щоб `CallbackHandler` міг обробити цю інформацію та повернути її користувачеві. Як тільки імплементація `CurrencyRateProvider` буде готова, можна буде дописати метод `handleGetInfo(long chatId, UserSettings userSettings)`. А також потрібно буде переконатися, що дефолтні налаштування застосовано, якщо користувач клацне «курси валют» перед вибором налаштувань.

2024-07-22 09:22 UTC, russtrUA requested changes
Залишив деякі зауваження по тексту файлів.

2024-07-22 09:22 UTC, russtrUA commented on src/main/java/com/app/telegram/features/bot/CurrencyRateBot.java
> +        callbackHandler = new CallbackHandler(telegramClient, currencyRateProvider);
CurrencyRateProvider буде доступний як Singleton через метод getInstance(). Тому його можно тут не створювати і не передавати в інші класи.

2024-07-22 09:22 UTC, russtrUA commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +        this.currencyRateProvider = new CurrencyRateProvider();
CurrencyRateProvider і UserSettingsProvider  будуть реалізовувати паттерн Singleton і їх об'єкти будуть доступні через метод getInstance().

2024-07-22 09:22 UTC, russtrUA commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +            case "NBU":
Було б добре не зашивати колбеки по банкам і валютам під конкретні значення. Наприклад, для банків можна відправляти колбек, який починається з callback_bank_ + Bank, де Bank - це один із списку Bank.values(). Щось типу такого if (call_data.startsWith("check_bank_")) {
                Bank bank = Bank.valueOf(call_data.substring(11));
Таким чином ми зможемо масштабувати проект на інші банки і валюти.

2024-07-22 09:22 UTC, russtrUA commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +        userSettings.setChosenBanks(List.of(Bank.valueOf(bankName)));
тут в тебе буде вибраний тільки якийсь один банк, але має бути можливість обрати кілька банків. Як з валютами.

2024-07-22 09:48 UTC, ruslanaprus commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +        this.currencyRateProvider = new CurrencyRateProvider();
Я переробила це так:
```Java
    public CallbackHandler(TelegramClient telegramClient) {
        this.telegramClient = telegramClient;
        this.userSettingsProvider = UserSettingsProvider.getInstance();
        this.currencyRateProvider = CurrencyRateProvider.getInstance();
    }

2024-07-22 09:54 UTC, ruslanaprus commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +        userSettings.setChosenBanks(List.of(Bank.valueOf(bankName)));
Я слідувала технічному завданню, там описано що вибір банків відбувається аналогічно до вибору знаків після коми

2024-07-22 10:01 UTC, ruslanaprus commented on src/main/java/com/app/telegram/features/bot/CurrencyRateBot.java
> +        callbackHandler = new CallbackHandler(telegramClient, currencyRateProvider);
Я змінила це так:
```Java
public CurrencyRateBot(String botToken) {
        telegramClient = new OkHttpTelegramClient(botToken);
        callbackHandler = new CallbackHandler(telegramClient);
    }

2024-07-22 10:15 UTC, ruslanaprus commented on src/main/java/com/app/telegram/features/bot/CallbackHandler.java
> +            case "NBU":
Я тут можу взяти назви банків з Bank enum, тоді щоб додати новий банк, достатньо буде це зробити додавши новий елемент у Bank enum

2024-07-24 09:31 UTC, russtrUA reviewed
наче все ок. Єдине питання написав стосовно зміни enum Bank.

2024-07-24 09:31 UTC, russtrUA commented on src/main/java/com/app/telegram/model/Bank.java
> +            case Pryvatbank -> "Pryvatbank";
а навіщо ти тут міняєш з кирилиці на латиницю? Ти ж можеш використовувати метод name() для значень enum, щоб отримати значення латиницею.

2024-07-24 09:35 UTC, russtrUA commented
Треба ще в конструкторі бота додати запуск потоку CurrencyRateThread за розкладом, наприклад, раз на 10 хвилин.

2024-07-24 09:36 UTC, russtrUA approved these changes

2024-07-24 14:27 UTC, ruslanaprus commented on src/main/java/com/app/telegram/model/Bank.java
> +            case Pryvatbank -> "Pryvatbank";
Я вже використовую метод name()
`keyboardRows.add(createRowWithCheck(bank.name(), bank.name(), isSelected));`

2024-07-24 16:14 UTC, ruslanaprus commented
> Треба ще в конструкторі бота додати запуск потоку CurrencyRateThread за розкладом, наприклад, раз на 10 хвилин.

Я додала `scheduler` для обох потоків `CurrencyRateThread` i `NotificationService`. Розклад для сповіщень я зробила так само як для `CurrencyRateThread`, ми можемо змінити його як тільки код `NotificationService` буде готовий
```
CurrencyRateThread currencyRateThread = new CurrencyRateThread();
NotificationService notificationService = new NotificationService(telegramClient);

ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(2);
scheduler.scheduleAtFixedRate(currencyRateThread, 0, 10, TimeUnit.MINUTES);
scheduler.scheduleAtFixedRate(notificationService, 0, 10, TimeUnit.MINUTES);
```

2024-07-24 17:02 UTC, merged